AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  umedispecialityapi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 3
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /speciality
            Method: GET
      Environment:
        Variables:
          PG_DB: umedi_dev
          PG_HOST: umedi-db.c9ta7oqd0sn5.ap-northeast-2.rds.amazonaws.com
          PG_PASSWORD: Umedi2023!!
          PG_USER: umedi
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      PackageType: Zip
